trigger:
- main
- development
- feature
- hotfix

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet tool"

    - task: DotNetCoreCLI@2
      displayName: "dotnet build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: "dotnet test"
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--no-build'