trigger:
- main
- development
- feature
- hotfix

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    
    - task: gitversion/setup@0
      displayName: 'Setup GitVersion'
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: 'Determine version'
      inputs:
        useConfigFile: true
        configFilePath: '$(System.DefaultWorkingDirectory)\src\GitVersion.yml'
    - task: UseDotNet@2
      displayName: 'Use .NET 6.x'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: "dotnet build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:Version=$(NuGetVersionV2)'

    - task: DotNetCoreCLI@2
      displayName: "dotnet test"
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--collect:"XPlat Code Coverage'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Agent.TempDirectory)/*/coverage.cobertura.xml

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/AzureDevops.Logger.csproj'
        nobuild: true
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'NuGetVersionV2'